name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make
      
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: source-file
        path: ebin
